module.exports = {
  apps: [
    {
      name: "thermalai-backend",
      script: "server.js",
      cwd: "./backend",
      watch: false,
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      restart_delay: 3000,
      max_memory_restart: "500M",
      error_file: "./logs/backend-error.log",
      out_file: "./logs/backend-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      env: { NODE_ENV: "production" },
    },
    {
      name: "thermalai-ml",
      script: "app.py",
      interpreter: "C:/Python313/python.exe",
      cwd: "./ml-model",
      watch: false,
      autorestart: true,
      max_restarts: 10,
      min_uptime: "15s",
      restart_delay: 5000,
      error_file: "./logs/ml-error.log",
      out_file: "./logs/ml-out.log",
    },
  ],
};
